src/resources/projects.js
Improove the employees function.
=> TG: Add employee function improove

.eslintrc.js, .husky/pre-commit, jest.config.js, jest.setup.js, package-lock.json, package.json, src/app.js, src/index.js
**Set Up description:**
> - Install DOTEnv
> - Install Jest / Supertest
> - Install mongodb-memory-server
> - Create `.env` file and move all the variables needed to that file (Port number - URL of database)
> - Create "Tests" folder into "src" and a file for each entity.
> - Create a "Seeds" folder into "src" and a file for each entity.
> - Update pre-commit  to run all test successfully before do commit (npm run test).
=> BaSP-TG-32: Set Up

babel.config.js, package.json, src/controllers/tasks.js, src/models/Tasks.js, src/seeds/tasks-seeds.js, src/tests/tasks.test.js, src/validations/tasks.js
**The following tickets were done in this PR:**
> - TG-51: updating model for tasks
> - TG-56: updating controllers for tasks
> - TG-53: linking Tasks collections (which was ignored because Tasks does not need it)
=> BaSP-TG-56: controllers, model and postman collection update

package.json, src/controllers/time-sheets.js, src/index.js, src/models/Time-sheets.js, src/validations/time-sheets.js
- Update timesheet with new path requirements
- Link collection to tasks, employees and projects collections
- Update validation to work on the new paths
- Update POST and PUT controllers to work with the new paths
=> Update timesheet schema, validations and controllers

.husky/pre-commit, src/controllers/tasks.js, src/routes/tasks.js, src/seeds/tasks-seeds.js, src/tests/admin.test.js, src/tests/admins.test.js, src/tests/employees.test.js, src/tests/members.test.js, src/tests/projects.test.js, src/tests/super-admins.test.js, src/tests/tasks.test.js, src/tests/time-sheets.test.js, src/validations/tasks.js
**This PR contains the following tickets:**
> - GET (TG-59): tests for getAll and getById.
> - POST (TG-60): tests for creating a task.
> - DELETE (TG-63): tests for deleting a task.
> - PUT (TG-61): tests for updating a task.
_**Tests:**_ 21 total.
=> BaSP-TG-59: Tests for Controllers

src/models/Projects.js, src/tests/projects.test.js
Modifications made to the projects schema on the server for an optimization in it's use in the front end
=> Hotfix-TG-156

package-lock.json, package.json, src/controllers/auth.js, src/helper/firebase/index.js, src/models/Users.js, src/routes/auth.js, src/routes/index.js, src/validations/auth.js
Implemented Firebase on the server:
- Install Firebase on server ('npm install firebase-admin')
- Add routes with middleware
- Add controllers
- Add validations
- Add models
- Index in helper/firebase
=> BaSP-TG-157: Implement Firebase on Server

src/controllers/admins.js, src/models/Admins.js, src/routes/admins.js, src/tests/admins.test.js, src/validations/admins.js
Done by @Lucas-DeLorenzi , i only do the PR because he can't right now.
- Update Model, add firebaseUid
- Update routes, add middleware
- Update controller.post, add auth features
- Create admin user and check with postman
=> BaSP-TG-185: Update Admin in server to authenticate

src/controllers/projects.js, src/routes/projects.js, src/tests/admins.test.js, src/tests/employees.test.js, src/tests/members.test.js, src/tests/projects.test.js, src/tests/super-admins.test.js, src/tests/tasks.test.js, src/tests/time-sheets.test.js
- Check if endpoints works well
- Update if necesary
- Update Middleware
- Added the fixes for bug report for Projects on ticket TG-117
=> BaSP-TG-166-117: Create and Update endpoints - Projects BE

src/controllers/admins.js, src/controllers/super-admins.js, src/models/Super-admins.js, src/routes/super-admins.js, src/seeds/super-admins-seeds.js, src/validations/super-admins.js
For more specific information, read the trello ticket: https://trello.com/c/UpTs7iDc/190-update-superadmin-be-with-new-data-model
=> TG-190: Update SUPERADMIN BE with new data model.

src/controllers/employees.js, src/models/Employees.js, src/routes/employees.js, src/seeds/employees-seeds.js, src/tests/employees.test.js, src/validations/employees.js
Done:
- TG-160: Create and Update endpoints - Employees BE [Ticket](https://trello.com/c/2mawbiyt/160-create-and-update-endpoints-employees-be)
```
1. Check if endopoints works well
2. Update it if necesary
3. Update middleware
```
- TG-115: BUGS Report: EMPLOYEE [Ticket](https://trello.com/c/dVh07iOt/115-bugs-report-employeel)
```
1. In the <employee> controllers, change the return messages in the json responses. Change "msg" to "message".
2. POST: Change message of create: "Status 200". Create a more specific and clear message. Example: "A new employee has been added successfully."
3. GET by id: Message is uninformative. Create a more specific and clear message. Example: "The employee with the ID has been found."
4. GET ALL: Change message: "Status 200". Create a more specific and clear …
```
=> BaSP-TG-160-115-191: Create and Update Endpoints - Employees BE

src/controllers/admins.js, src/controllers/members.js, src/controllers/super-admins.js, src/models/Members.js, src/models/Super-admins.js, src/routes/super-admins.js, src/seeds/members-seeds.js, src/seeds/super-admins-seeds.js, src/validations/members.js, src/validations/super-admins.js
Fore more specific information, read the trello ticket: https://trello.com/c/b3ZXqUjh/194-update-members-be-with-new-data-model
=> TG-194: Update MEMBERS BE with new data model.

src/controllers/admins.js, src/models/Admins.js, src/routes/admins.js, src/seeds/admins-seeds.js, src/tests/admin.test.js, src/tests/admins.test.js, src/validations/admins.js
Done:
- TG-164: Create and Update endpoints - Admins BE [Ticket](https://trello.com/c/8QJI7V2k/164-create-and-update-endpoints-admins-be)
```
1. Check if endopoints works well
2. Update it if necesary
3. Update middleware
```
- TG-114: BUGS Report: ADMIN [Ticket](https://trello.com/c/XFFXlkvp/114-bugs-report-admin)
```
1. In the <admin> controllers, change the return messages in the json responses. Change "msg" to "message".
2. GET by id: Message is uninformative. Create a more specific and clear message. Example: "The admin with the ID has been found."
3. GET ALL: Change message: "Status 200". Create a more specific and clear message. Example: "Admin list displayed correctly."
4. <CONTROLLERS-ADMIN> Lines: From 45 to 52. Delete all comments.
```
- TG-189: Update ADMIN BE with new data …
=> BaSP-TG-164-189-114: Create and Update endpoints - Admins BE

src/controllers/projects.js, src/controllers/time-sheets.js, src/models/Members.js, src/models/Projects.js, src/routes/employees.js, src/routes/members.js, src/routes/projects.js, src/seeds/projects-seeds.js, src/tests/projects.test.js, src/validations/members.js, src/validations/projects.js
TG-192: [Ticket](https://trello.com/c/1ctNqZ4K/192-update-projects-be-with-new-data-model)
Done:
```
- Check that the resource schema follows the new data model(with already decided variations to populate succesfully on GET). Update if necessary.
- Modify controllers.
- Modify validations.
- Check that the changes work (Postman)
```
=> BaSP-TG-192: Update PROJECTS BE with new data model

src/controllers/admins.js, src/controllers/employees.js, src/controllers/super-admins.js
Added firebase delete method for each user role:
- Admin
- SuperAdmin
- Employee
=> TG-205: firebase delete method

src/controllers/time-sheets.js
<TIME-SHEET> POST: Success message changed to: "Timesheet successfully created".
<TIME-SHEET> PUT-Update: Success message changed to: "Timesheet successfully updated".
<TIME-SHEET> DELETE: Success message changed to: "Timesheet successfully deleted"
** Other bug fix indications from ticket TG-118 were solved in the TG-123 ticket**
=> BaSP-TG-118: Bug fix for timesheets

src/models/Projects.js
Update Project schema and validation in server to remove required opcion in Member and PM props
=> BaSP-TG-226: Remove required options

src/routes/time-sheets.js, src/validations/time-sheets.js
[Ticket of Trello](https://trello.com/c/psgYxGib/231-add-a-validation-to-put-controller-on-timesheet-be)
=> BaSP-TG-231: Add a validation to put controller on Timesheet BE

src/models/Projects.js, src/routes/projects.js, src/seeds/super-admins-seeds.js, src/validations/projects.js
- the API now allows to create projects without PM and members
=> Hotfix-TG-230: Project Schema and validations fix

src/controllers/admins.js, src/controllers/employees.js, src/controllers/members.js, src/controllers/projects.js, src/controllers/super-admins.js, src/controllers/tasks.js, src/controllers/time-sheets.js, src/models/Projects.js
[Ticket](https://trello.com/c/MqchFqzx/233-change-project-data-model-be)
- Data model change: pm should stop being popularized with members and should be popularized with employees.
- Project get all must allow to use req params find.
- Add filters of query to get all methods
=> Basp-TG-233: Change project Data model BE & get all methods of all entities

src/controllers/admins.js, src/controllers/employees.js, src/controllers/members.js, src/controllers/projects.js, src/controllers/super-admins.js, src/controllers/tasks.js, src/controllers/time-sheets.js, src/models/Employees.js, src/routes/projects.js, src/validations/employees.js, src/validations/members.js
Added changes to msg of bodys of response on each entity and changes to put of employee, employee model and validation.
=> BaSP-TG-242: Changes to BE
